require: rubocop-rails

AllCops:
  Exclude:
  - '**/tmp/**/*'
  - '**/templates/**/*'
  - '**/vendor/**/*'
  - '**/bin/**/*'
  - 'actionpack/lib/action_dispatch/journey/parser.rb'
  - 'actionmailbox/test/dummy/**/*'
  - 'actiontext/test/dummy/**/*'
  - '**/node_modules/**/*'
  - 'db/schema.rb'
  - 'db/migrate/*'
  - 'config/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
