# Configure Using Gemfile
# gem "pg"
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: postgres
  password: postgres

development:
  <<: *default
  database: flash_cards_development

test:
  <<: *default
  database: flash_cards_test

production:
  <<: *default
  database: flash_cards_production
  username: flash_cards
  password: <%= ENV["FLASH_CARDS_DATABASE_PASSWORD"] %>
